### ISSUE TITLE
jsonp

### ISSUE THREAD

**Issue by blake41** [learn-co-curriculum/js-apis-readme#2]
**if we use jsonp datatype we should explain what that is/means**
$.ajax({
    url: 'https://api.github.com/repos/rails/rails/stargazers',
    type: 'POST',
    dataType: 'jsonp'
  }).done(function(response) {
    var users = response.data;
    printStargazers(users);
  });

**Comment by pletcher** [comment]
(note to self) JSON-P should probably be its own lesson if we want to cover it.
